// DET Practice — question banks
// All content original, modeled on official 2026 task formats.

const DATA = {

// ───────────────────────── Interactive Speaking ─────────────────────────
// One session = one topic, 3–4 follow-ups. Question is read aloud ONCE, then 35s to answer.
interactiveSpeaking: [
  { topic: "Daily routine", questions: [
    "What does a typical weekday look like for you?",
    "Which part of your day do you enjoy the most, and why?",
    "If you could change one thing about your daily schedule, what would it be?",
    "How is your weekend routine different from your weekday routine?",
  ]},
  { topic: "Technology", questions: [
    "How often do you use your phone, and what do you mainly use it for?",
    "Do you think people depend too much on technology? Why or why not?",
    "Tell me about an app or device that has made your life easier.",
    "How do you think technology will change education in the next ten years?",
  ]},
  { topic: "Food and cooking", questions: [
    "Do you prefer cooking at home or eating out? Why?",
    "Describe a dish from your culture that you would recommend to a visitor.",
    "Has the way you eat changed since you moved or started studying? How?",
    "If you had to teach someone one recipe, what would it be and why?",
  ]},
  { topic: "Travel", questions: [
    "What is the most memorable place you have ever visited?",
    "Do you prefer traveling alone or with other people? Why?",
    "What do you usually do to prepare before a trip?",
    "If you could live in another country for a year, where would you go and why?",
  ]},
  { topic: "Friendship", questions: [
    "How did you meet your closest friend?",
    "What qualities do you value most in a friend?",
    "Is it easier or harder to make friends as an adult? Why do you think so?",
    "How do you stay in touch with friends who live far away?",
  ]},
  { topic: "Study habits", questions: [
    "Where do you usually study, and why does that place work for you?",
    "Do you study better in the morning or at night? Why?",
    "How do you stay focused when a task is boring?",
    "What advice about studying would you give to a new college student?",
  ]},
  { topic: "Hobbies", questions: [
    "What do you like to do in your free time?",
    "How did you first get interested in that hobby?",
    "Do you think hobbies are important for a balanced life? Why?",
    "Is there a new skill or hobby you would like to learn? What is stopping you?",
  ]},
  { topic: "Hometown", questions: [
    "Tell me about the place where you grew up.",
    "What do you miss most about your hometown?",
    "How has your hometown changed over the years?",
    "Would you recommend your hometown as a place to live? Why or why not?",
  ]},
  { topic: "Work and career", questions: [
    "What kind of job would you like to have in the future?",
    "Do you think salary or job satisfaction is more important? Why?",
    "Tell me about a project or job you worked on that you are proud of.",
    "Would you prefer working from home or in an office? Why?",
  ]},
  { topic: "Movies and entertainment", questions: [
    "What kind of movies or shows do you enjoy watching?",
    "Tell me about a movie that left a strong impression on you.",
    "Do you prefer watching things alone or with friends? Why?",
    "Do you think streaming services have changed how people watch movies? How?",
  ]},
  { topic: "Health and exercise", questions: [
    "What do you do to stay healthy?",
    "Do you think students get enough exercise? Why or why not?",
    "Tell me about a time you tried to build a healthy habit. What happened?",
    "If your city wanted to help people exercise more, what should it do?",
  ]},
  { topic: "Languages", questions: [
    "How long have you been learning English, and how did you start?",
    "What is the hardest part of learning a new language for you?",
    "Do you think everyone should learn a second language? Why?",
    "What methods have helped you improve your English the most?",
  ]},
  { topic: "Big decisions", questions: [
    "Tell me about an important decision you made recently.",
    "Do you usually make decisions quickly or slowly? Why?",
    "Who do you ask for advice when you face a difficult choice?",
    "Have you ever regretted a decision? What did you learn from it?",
  ]},
  { topic: "City life", questions: [
    "Do you prefer living in a big city or a small town? Why?",
    "What is the biggest problem in the city where you live now?",
    "How do you usually get around your city?",
    "If you were the mayor for a day, what would you change first?",
  ]},
  { topic: "Shopping", questions: [
    "Do you prefer shopping online or in physical stores? Why?",
    "Tell me about something you bought recently that you really like.",
    "Have you ever regretted buying something? What happened?",
    "How do you decide whether something is worth the price?",
  ]},
  { topic: "Music", questions: [
    "What kind of music do you usually listen to?",
    "When do you listen to music during your day?",
    "Have you ever played a musical instrument? Tell me about it.",
    "Do you think music helps people study, or does it distract them?",
  ]},
  { topic: "Weather and seasons", questions: [
    "What is your favorite season, and why?",
    "How does the weather affect your mood or your plans?",
    "Tell me about a time when bad weather changed your plans.",
    "Would you rather live somewhere always hot or always cold? Why?",
  ]},
  { topic: "Family", questions: [
    "Who in your family are you closest to?",
    "What is a tradition or habit your family has?",
    "How often do you talk to your family, and what do you talk about?",
    "What is something important you learned from your parents?",
  ]},
  { topic: "Pets and animals", questions: [
    "Do you have a pet, or would you like to have one?",
    "What do you think are the benefits of keeping a pet?",
    "Some apartments do not allow pets. Do you think that is fair?",
    "If you could be any animal for a day, which would you choose and why?",
  ]},
  { topic: "Social media", questions: [
    "Which social media apps do you use the most?",
    "Do you think you spend too much time on social media? Why?",
    "Have you ever taken a break from social media? How did it feel?",
    "Should children under thirteen be allowed to use social media? Why or why not?",
  ]},
  { topic: "Books and reading", questions: [
    "Do you enjoy reading? What kind of books do you like?",
    "Tell me about a book that influenced you.",
    "Do you prefer paper books or e-books? Why?",
    "Why do you think some people read less now than in the past?",
  ]},
  { topic: "Sports", questions: [
    "Do you play any sports, or do you prefer watching them?",
    "Tell me about a memorable game or match you watched or played.",
    "Do you think schools should require students to play sports? Why?",
    "Which is more important in sports, talent or hard work? Why?",
  ]},
  { topic: "Transportation", questions: [
    "How do you usually get to school or work?",
    "What do you like and dislike about public transportation in your area?",
    "Have you ever had a terrible travel experience on the way somewhere? What happened?",
    "Do you think cars should be banned from city centers? Why or why not?",
  ]},
  { topic: "Holidays", questions: [
    "What is your favorite holiday, and how do you celebrate it?",
    "Do you prefer spending holidays with family or with friends? Why?",
    "Tell me about a holiday memory you will never forget.",
    "Do you think holidays have become too commercial? Why or why not?",
  ]},
  { topic: "Money and saving", questions: [
    "Are you a saver or a spender? Give me an example.",
    "What was the best money you ever spent? Why was it worth it?",
    "Do you think students should learn about money management in school?",
    "If you suddenly received a thousand dollars, what would you do with it?",
  ]},
  { topic: "Roommates and neighbors", questions: [
    "Have you ever lived with a roommate? What was it like?",
    "What qualities make someone a good roommate?",
    "Tell me about a disagreement you had with a roommate or neighbor.",
    "Do you prefer living alone or with other people? Why?",
  ]},
  { topic: "Nature and environment", questions: [
    "Do you spend much time outdoors? What do you do?",
    "What environmental problem worries you the most?",
    "What small things do you do to protect the environment?",
    "Should the government charge extra for plastic bags? Why or why not?",
  ]},
  { topic: "Celebrations", questions: [
    "How do you usually celebrate your birthday?",
    "Tell me about the best party or celebration you have ever attended.",
    "Do you prefer big celebrations or small ones? Why?",
    "Is it better to give gifts or to receive them? Why?",
  ]},
  { topic: "Future plans", questions: [
    "Where do you see yourself in five years?",
    "What is one skill you want to learn in the next year?",
    "Do you prefer to plan ahead or go with the flow? Why?",
    "What is one dream you had as a child that has changed?",
  ]},
  { topic: "Childhood memories", questions: [
    "What did you enjoy doing most as a child?",
    "Tell me about a place you loved when you were young.",
    "What is something you believed as a child that turned out to be wrong?",
    "How is your life now different from what you imagined as a child?",
  ]},
],

// ───────────────────────── Read Then Speak ─────────────────────────
// 20s prep + 90s speaking. Prompt stays visible.
readThenSpeak: [
  { prompt: "Talk about a teacher who influenced you.", bullets: ["Who was the teacher and what did they teach?", "What did they do that was special?", "How did they influence your life?"] },
  { prompt: "Describe a time when you had to learn something difficult.", bullets: ["What were you learning and why?", "What made it difficult?", "How did you finally succeed?"] },
  { prompt: "Talk about a place where you feel relaxed.", bullets: ["Where is it and what does it look like?", "What do you do there?", "Why does it make you feel calm?"] },
  { prompt: "Describe a goal you are working toward right now.", bullets: ["What is the goal?", "Why is it important to you?", "What steps are you taking to achieve it?"] },
  { prompt: "Talk about a time you helped someone.", bullets: ["Who did you help and what was the situation?", "What did you do?", "How did you feel afterward?"] },
  { prompt: "Describe a tradition or celebration in your culture.", bullets: ["What is the tradition?", "How do people celebrate it?", "Why is it meaningful to you?"] },
  { prompt: "Talk about a piece of advice you received that you still remember.", bullets: ["Who gave you the advice?", "What was the advice?", "How has it affected your decisions?"] },
  { prompt: "Describe a time when something did not go as planned.", bullets: ["What were you planning to do?", "What went wrong?", "How did you handle it and what did you learn?"] },
  { prompt: "Talk about a skill that everyone should learn.", bullets: ["What is the skill?", "Why is it useful in daily life?", "How can someone start learning it?"] },
  { prompt: "Describe an object that is important to you.", bullets: ["What is it and where did you get it?", "What do you use it for?", "Why does it matter so much to you?"] },
  { prompt: "Explain what recursion is, as if to a first-year student.", bullets: ["What does recursion mean in simple words?", "Give an everyday example or analogy.", "When is recursion useful in programming?"] },
  { prompt: "Explain what an operating system does, for someone who is not a computer science major.", bullets: ["What is an operating system?", "Give examples people use every day.", "What main jobs does it do behind the scenes?"] },
  { prompt: "Explain why algorithms matter, to a high school student.", bullets: ["What is an algorithm in simple terms?", "Give a real-life example of an algorithm.", "Why does choosing a better algorithm matter?"] },
  { prompt: "Explain what the cloud is, for someone who only uses a phone.", bullets: ["What does 'the cloud' actually mean?", "Give examples of cloud services people already use.", "What are one advantage and one risk?"] },
  { prompt: "Explain how the internet delivers a web page, in simple terms.", bullets: ["What happens when you type a website address?", "Use an analogy such as sending a letter.", "Why does a page sometimes load slowly?"] },
  { prompt: "Talk about whether students should be required to take public speaking classes.", bullets: ["What is your opinion?", "Give a reason with an example.", "What would you say to someone who disagrees?"] },
  { prompt: "Describe a time when you worked with a team.", bullets: ["What was the project or activity?", "What was your role?", "What did you learn about teamwork?"] },
  { prompt: "Talk about how you manage stress during busy periods.", bullets: ["When do you usually feel the most stress?", "What strategies do you use?", "Which strategy works best, and why?"] },
  { prompt: "Describe a time when you received good customer service.", bullets: ["Where were you and what did you need?", "What did the staff do?", "How did it change your opinion of the place?"] },
  { prompt: "Talk about a habit you would like to change.", bullets: ["What is the habit?", "Why do you want to change it?", "What have you tried so far?"] },
  { prompt: "Describe a memorable meal you have had.", bullets: ["Where were you and who were you with?", "What did you eat?", "Why was it so memorable?"] },
  { prompt: "Talk about a time you taught someone how to do something.", bullets: ["Who did you teach and what was the skill?", "How did you explain it?", "What did you learn from teaching?"] },
  { prompt: "Describe a website or app you use almost every day.", bullets: ["What is it and what does it do?", "How does it make your life easier?", "What would you improve about it?"] },
  { prompt: "Talk about a time you were surprised by something.", bullets: ["What happened?", "How did you react?", "Why was it so unexpected?"] },
  { prompt: "Describe your ideal place to live.", bullets: ["Where would it be, city or countryside?", "What would the home itself be like?", "Why does this environment suit you?"] },
  { prompt: "Talk about an important news story you followed recently.", bullets: ["What was the story about?", "How did you follow it?", "Why did it matter to you?"] },
  { prompt: "Describe a time you had to speak in front of many people.", bullets: ["What was the occasion?", "How did you prepare and feel?", "What would you do differently next time?"] },
  { prompt: "Talk about something you own that you should probably throw away.", bullets: ["What is it?", "Why do you still keep it?", "What would make you finally let it go?"] },
  { prompt: "Describe a person in your community you admire.", bullets: ["Who are they and what do they do?", "What have they done for others?", "How have they influenced you?"] },
  { prompt: "Talk about a time you got lost.", bullets: ["Where were you trying to go?", "How did you realize you were lost?", "How did you find your way?"] },
  { prompt: "Describe a class or course you really enjoyed.", bullets: ["What was the subject?", "What made the class enjoyable?", "How has it been useful since?"] },
  { prompt: "Talk about the role of breakfast in your day.", bullets: ["What do you usually eat in the morning?", "How does it affect your energy?", "What would your perfect breakfast be?"] },
  { prompt: "Describe a time when you had too many things to do.", bullets: ["What was the situation?", "How did you decide what to do first?", "What did you learn about managing time?"] },
  { prompt: "Talk about a gift you gave that the person really loved.", bullets: ["What was the gift and who was it for?", "How did you choose it?", "How did they react?"] },
  { prompt: "Describe a problem in your neighborhood and how it could be solved.", bullets: ["What is the problem?", "Who does it affect?", "What is your suggested solution?"] },
  { prompt: "Talk about a time you worked very hard for something.", bullets: ["What was your goal?", "What sacrifices did you make?", "Was it worth it in the end?"] },
  { prompt: "Describe an outdoor activity you enjoy.", bullets: ["What is the activity?", "When and where do you do it?", "Why do you prefer it to indoor activities?"] },
  { prompt: "Talk about a stranger who helped you once.", bullets: ["What was the situation?", "What did the stranger do?", "How did it affect how you treat others?"] },
  { prompt: "Explain how you would describe the internet to someone from one hundred years ago.", bullets: ["What comparison would you start with?", "What examples would you give?", "What would be hardest for them to believe?"] },
  { prompt: "Explain what artificial intelligence is to a grandparent.", bullets: ["What is AI in everyday words?", "What examples do they already use?", "What is one thing AI cannot do well?"] },
  { prompt: "Explain why computers use passwords, to a young child.", bullets: ["What is a password for?", "Use a simple comparison, like a key.", "What makes a password strong?"] },
  { prompt: "Explain what a database is, for someone who has never studied computers.", bullets: ["What does a database store?", "Give a real-life comparison.", "Where do people meet databases in daily life?"] },
  { prompt: "Explain why software has bugs, to a non-technical friend.", bullets: ["What is a bug?", "Why can't programmers avoid them completely?", "How do teams find and fix them?"] },
  { prompt: "Talk about whether homework should be limited.", bullets: ["What is your opinion?", "Give a reason with an example.", "What would you say to a teacher who disagrees?"] },
  { prompt: "Talk about whether everyone should learn to cook.", bullets: ["What is your opinion?", "How does cooking affect health and money?", "What dish should everyone learn first?"] },
  { prompt: "Talk about whether museums should be free.", bullets: ["What is your opinion?", "Who benefits from free museums?", "How else could museums earn money?"] },
  { prompt: "Talk about whether students should take a gap year before university.", bullets: ["What is your opinion?", "What can people gain from a gap year?", "What are the risks?"] },
  { prompt: "Talk about whether it is better to rent or to buy a home.", bullets: ["Which do you think is better?", "Give a financial reason.", "Give a lifestyle reason."] },
],

// ───────────────────────── Speaking Sample ─────────────────────────
// 30s prep + up to 3 minutes. Sent to schools with the score report.
speakingSample: [
  "Some people believe that universities should require all students to take courses outside their major. Do you agree or disagree? Use reasons and examples to support your opinion.",
  "Many people think that failure is a better teacher than success. What do you think? Support your answer with examples from your own experience.",
  "Some students prefer to study alone, while others prefer studying in groups. Which do you prefer, and why? Use specific examples.",
  "Do you think social media brings people closer together or pushes them further apart? Explain your opinion with reasons and examples.",
  "Some people say that technology makes us less creative. Do you agree or disagree? Support your view with examples.",
  "Is it better to have a few close friends or many casual acquaintances? Explain your choice with reasons and personal examples.",
  "Some people believe that students learn more from teachers, while others believe they learn more from experience. What is your view?",
  "Should universities make attendance optional for all lectures? Explain your opinion with reasons and examples.",
  "Many people believe that learning a foreign language should be required in every school. Do you agree? Why or why not?",
  "Is it more important for a job to pay well or to be enjoyable? Explain your opinion with reasons and examples.",
  "Some people think working while studying is valuable, while others think students should focus only on school. What do you think?",
  "Do you think artificial intelligence will create more opportunities or more problems for your generation? Explain with examples.",
  "Some people believe that everyone should spend time living away from their hometown. Do you agree or disagree? Use examples.",
  "Is it better to make decisions based on logic or based on feelings? Explain your opinion with examples from your life.",
  "Some people think that modern technology makes people more lonely. Do you agree or disagree? Support your view.",
  "Should universities spend more money on sports facilities or on libraries? Explain your choice with reasons.",
  "Many people believe that travel is the best form of education. Do you agree or disagree? Use specific examples.",
  "Some people prefer jobs with flexible hours, while others prefer a fixed schedule. Which do you prefer and why?",
  "Do you think famous people have a responsibility to be good role models? Explain your opinion.",
  "Is it more important to be respected or to be liked? Explain your view with examples.",
  "Some people say that printed books will disappear in the future. Do you agree? Why or why not?",
  "Should governments spend money on art and culture, or should that money go to more practical things? Explain.",
  "Some people believe children today grow up too quickly. Do you agree or disagree? Support your answer.",
  "Is competition or cooperation more important for success in life? Explain with examples.",
  "Some people think the best way to relax is to do nothing, while others prefer active hobbies. What do you think?",
  "Do you think people should follow the same career for their whole life, or change careers several times? Explain.",
  "Some people believe that mistakes are necessary for learning. Do you agree or disagree? Use personal examples.",
  "Should public transportation be free for everyone? Explain your opinion with reasons and examples.",
  "Some people say it is better to be a big fish in a small pond than a small fish in a big pond. What do you think?",
  "Do you think handwriting is still an important skill? Why or why not?",
  "Some people believe that the older generation has little to teach the younger generation about modern life. Do you agree?",
  "Is it better to do many things at an average level or one thing extremely well? Explain your view.",
],

// ───────────────────────── Listen and Type ─────────────────────────
// Sentence read aloud (max 3 plays), type exactly what you hear.
listenAndType: [
  "The library closes early on Friday evenings.",
  "She decided to walk to campus instead of taking the bus.",
  "Our professor canceled the lecture because of the storm.",
  "Please remember to submit your assignment before midnight.",
  "The new student center will open at the beginning of next semester.",
  "He has been studying English for almost six years.",
  "The results of the experiment surprised everyone in the lab.",
  "Most students prefer online registration because it saves time.",
  "The museum offers free admission on the first Sunday of every month.",
  "I forgot my umbrella, so I waited until the rain stopped.",
  "The committee will announce its final decision next Tuesday afternoon.",
  "Researchers discovered that regular exercise improves memory and concentration.",
  "The flight was delayed for two hours because of heavy fog.",
  "You should back up your files before updating the software.",
  "The cafeteria introduced several vegetarian options this semester.",
  "Although the test was difficult, most students finished it on time.",
  "The city plans to build a new bridge across the river next year.",
  "Her presentation covered the history of renewable energy in Europe.",
  "If you have any questions, please contact the office before noon.",
  "The bookstore is offering a discount on used textbooks this week.",
  "Scientists are still trying to understand how the brain stores memories.",
  "He apologized for the mistake and promised to correct it immediately.",
  "The orchestra will perform in the main auditorium on Saturday night.",
  "Students who miss more than three classes may lose participation points.",
  "The recipe requires two cups of flour and a teaspoon of salt.",
  "We watched the sunset from the roof of the tallest building in town.",
  "The company announced that it would hire fifty new engineers this year.",
  "Despite the traffic, they arrived at the airport with time to spare.",
  "The lecture on climate change attracted students from many different departments.",
  "Please turn off your phone before the performance begins.",
  "The hiking trail was closed because of falling rocks near the summit.",
  "She borrowed three books about modern architecture from the library.",
  "The deadline for scholarship applications has been extended by one week.",
  "Drinking enough water during the day helps you stay focused.",
  "The train to the city center leaves every fifteen minutes during rush hour.",
  "He spent the whole weekend preparing for his chemistry final.",
  "The hotel offers free breakfast and a shuttle to the conference center.",
  "Volunteers planted more than a hundred trees in the park last spring.",
  "The instructions were so confusing that nobody could assemble the furniture.",
  "Her research focuses on how children learn their first language.",
  "The professor asked everyone to turn in their essays by Friday.",
  "There is a free shuttle bus between the two campuses every half hour.",
  "He couldn't remember where he had parked his car.",
  "The art exhibition will run until the end of the month.",
  "She practices the piano for an hour every morning before work.",
  "The store was out of milk, so I bought some at the market next door.",
  "Many students find it difficult to balance work and study.",
  "The committee rejected the proposal because it was too expensive.",
  "Remember to bring your passport and a printed copy of your ticket.",
  "The temperature dropped suddenly, and it started to snow.",
  "He has visited more than twenty countries in the past ten years.",
  "The lecture hall was so crowded that some students had to stand.",
  "You can renew your library books online or at the front desk.",
  "The bakery on the corner sells fresh bread every morning.",
  "Her flight arrives at seven, so we should leave for the airport by six.",
  "Scientists believe the new vaccine could save millions of lives.",
  "The manager apologized for the delay and offered everyone free coffee.",
  "Please read the first three chapters before our next meeting.",
  "The children spent the afternoon building a treehouse in the garden.",
  "Electric cars are becoming more popular as battery prices fall.",
  "She was offered the job, but she decided to stay at her current company.",
  "The bridge is closed for repairs, so we have to take the long way around.",
  "Most of the students passed the exam on their first attempt.",
  "The museum's new wing will display photographs from the last century.",
  "He turned off the alarm and went straight back to sleep.",
  "The total cost includes breakfast, taxes, and airport transfers.",
  "Heavy rain caused flooding in several parts of the city.",
  "She translated the document from French into English for her boss.",
  "The team celebrated their victory with a dinner downtown.",
  "Applications received after the deadline will not be considered.",
  "I usually take notes on my laptop, but sometimes I prefer paper.",
  "The hotel upgraded our room because the air conditioning was broken.",
  "Researchers spent five years collecting data for the study.",
  "The concert was postponed because the singer lost her voice.",
  "You will need a student card to use the gym and the swimming pool.",
  "The recipe has been in our family for three generations.",
  "Traffic was terrible this morning because of an accident on the highway.",
  "The professor explained the theory again for those who had missed class.",
  "We adopted a dog from the shelter two years ago.",
  "The company plans to open three new offices in Asia next year.",
  "Could you water my plants while I am away next week?",
  "The exam will cover everything we have studied since September.",
  "Prices at the campus bookstore are higher than online.",
  "He fixed the leak in the bathroom without calling a plumber.",
  "The orchestra needs two more violinists for the spring concert.",
  "My grandmother taught me how to knit when I was ten.",
  "The meeting has been moved from Tuesday to Thursday afternoon.",
  "A balanced diet and regular sleep are essential for good health.",
  "The students organized a fundraiser to support the local food bank.",
  "It took them nearly three hours to assemble the bookshelf.",
  "The island can only be reached by boat or helicopter.",
  "She forgot her password and had to reset it twice.",
  "The coach canceled practice because the field was too muddy.",
  "Volunteers cleaned up the beach and collected forty bags of trash.",
  "The new policy allows employees to work from home two days a week.",
  "His phone battery died right in the middle of the interview.",
  "The garden looks beautiful now that the roses are in bloom.",
  "Tickets for the festival usually sell out within a few hours.",
  "I left a note on the fridge to remind everyone about the party.",
],

// ───────────────────────── Summarize the Conversation ─────────────────────────
// Listen to a short campus conversation, then 75s to type a summary.
summarize: [
  { title: "Late assignment", lines: [
    ["Student", "Professor Lee, I'm really sorry, but I couldn't finish the essay. My laptop crashed last night and I lost part of my draft."],
    ["Professor", "I'm sorry to hear that. Did you try the computer lab in the library? They have recovery software."],
    ["Student", "I didn't know that. Could I have two more days to rewrite the lost section?"],
    ["Professor", "I can give you until Thursday at noon, but please email the IT desk today so there's a record of the crash."],
    ["Student", "That's fair. I'll contact them right away. Thank you so much."],
  ]},
  { title: "Choosing a course", lines: [
    ["Student", "Hi, I'm trying to decide between Statistics and Linear Algebra next semester. Which one would you recommend?"],
    ["Advisor", "It depends on your goals. If you're leaning toward data science, statistics is more directly useful."],
    ["Student", "I am interested in data science, but I heard the statistics professor gives a lot of homework."],
    ["Advisor", "That's true, but the homework is exactly why students do well later. You could also take linear algebra in the summer."],
    ["Student", "Good idea. I'll register for statistics now and plan linear algebra for summer."],
  ]},
  { title: "Dorm noise problem", lines: [
    ["Student", "Hi, I'd like to report a problem. My neighbors play loud music almost every night, and I can't sleep."],
    ["Staff", "Have you talked to them directly about it?"],
    ["Student", "I tried once, but it only got better for a few days. Now it's worse again, especially during exam week."],
    ["Staff", "Okay. I'll send a formal notice today, and if it continues this weekend, call the front desk and we'll document it."],
    ["Student", "Thank you. I just want quiet after eleven at night."],
  ]},
  { title: "Joining a research lab", lines: [
    ["Student", "Professor, I really enjoyed your machine learning class. Are there any openings in your lab for undergraduates?"],
    ["Professor", "Possibly. We have a project on speech recognition that needs help with data cleaning."],
    ["Student", "That sounds great. I know Python and I've used pandas in two courses."],
    ["Professor", "Good. Send me your resume and transcript tonight, and come to our lab meeting on Friday at three."],
    ["Student", "I'll be there. Thank you for the opportunity."],
  ]},
  { title: "Gym membership", lines: [
    ["Student", "Hi, I'd like to cancel my gym membership. I'm graduating next month."],
    ["Staff", "Congratulations! You can cancel, but actually graduating students get a free extension until the end of August."],
    ["Student", "Really? I didn't know that. Is there any paperwork?"],
    ["Staff", "Just bring your student ID and fill out a one-page form at the front desk before your graduation date."],
    ["Student", "Perfect, I'll keep the membership then. Thanks for letting me know."],
  ]},
  { title: "Group project conflict", lines: [
    ["Student A", "Hey, we need to talk about the project. You missed our last two meetings and the deadline is Friday."],
    ["Student B", "I'm really sorry. I've been working extra shifts because my rent went up."],
    ["Student A", "I understand, but we still need your part of the presentation. Can you finish the slides by Wednesday?"],
    ["Student B", "Yes, I'm off Tuesday night. I'll send them Wednesday morning and I can present that section too."],
    ["Student A", "Okay, that works. Let's do a quick video call Thursday to rehearse."],
  ]},
  { title: "Lost and found", lines: [
    ["Student", "Excuse me, I think I left my backpack in this lecture hall yesterday afternoon. It's dark blue with a red keychain."],
    ["Staff", "Let me check the lost and found. Was anything valuable inside?"],
    ["Student", "My laptop and my calculus textbook. I really need them for an exam tomorrow."],
    ["Staff", "You're lucky — a cleaner turned in a blue backpack last night. Can you show me your student ID and describe the laptop?"],
    ["Student", "It's a silver laptop with a physics sticker on the lid. Here's my ID. Thank you so much!"],
  ]},
  { title: "Internship advice", lines: [
    ["Student", "Hi, I got two internship offers and I don't know which to accept. One pays more, but the other matches my major."],
    ["Advisor", "Which one offers better mentorship and real projects?"],
    ["Student", "The lower-paying one. The team said I'd build a real feature, not just observe."],
    ["Advisor", "Then I'd choose that one. Early in your career, experience and references matter more than a small pay difference."],
    ["Student", "That makes sense. I'll accept it today before the deadline."],
  ]},
  { title: "Printer problem", lines: [
    ["Student", "Excuse me, the printer on the second floor ate my money again. I paid for ten pages and got nothing."],
    ["Staff", "Sorry about that. It's been jamming all week. Did you use your campus card or coins?"],
    ["Student", "My campus card. I really need these pages for a class in twenty minutes."],
    ["Staff", "Use the printer in the basement computer lab — it's working. I'll refund your card now, just sign this form."],
    ["Student", "Perfect, thank you. I'll go to the basement right away."],
  ]},
  { title: "Meal plan change", lines: [
    ["Student", "Hi, I'd like to switch to a smaller meal plan. I barely use half of my current one."],
    ["Staff", "You can downgrade, but changes only take effect at the start of next month."],
    ["Student", "That's fine. Will I get money back for the unused meals this month?"],
    ["Staff", "Unused meals don't roll over, unfortunately. But you can use extra swipes to buy snacks at the campus store before the thirty-first."],
    ["Student", "Good to know. Please switch me to the smaller plan starting next month, and I'll spend the rest on snacks."],
  ]},
  { title: "Midterm regrade", lines: [
    ["Student", "Professor, I think there's a mistake in my midterm grade. Question five was marked wrong, but my answer matches the textbook."],
    ["Professor", "Let me see. Hmm, you used a different method, but the result looks correct."],
    ["Student", "I used the formula from chapter three instead of chapter four."],
    ["Professor", "Fair enough. I'll send a regrade request to the teaching assistant today, and you should see the updated score by Monday."],
    ["Student", "Thank you so much. Those four points really matter for my scholarship."],
  ]},
  { title: "Study abroad application", lines: [
    ["Student", "Hi, I'm interested in the exchange program in Spain, but I missed the information session."],
    ["Advisor", "No problem. The application is due March first, and you need one recommendation letter and a short essay."],
    ["Student", "Does my Spanish need to be fluent? I've only studied it for two years."],
    ["Advisor", "Two years is enough for the Madrid program. The Barcelona one requires an advanced certificate, though."],
    ["Student", "Madrid it is, then. I'll ask my Spanish professor for the recommendation letter this week."],
  ]},
  { title: "Club funding request", lines: [
    ["Student", "Hi, I'm the treasurer of the photography club. We'd like to request funding for a weekend workshop."],
    ["Staff", "How much do you need, and how many students will participate?"],
    ["Student", "About three hundred dollars for materials, and we expect twenty-five students."],
    ["Staff", "That's within the limit, but you'll need to submit the request form and a budget breakdown at least two weeks before the event."],
    ["Student", "The workshop is in a month, so we have time. I'll bring the forms tomorrow."],
  ]},
  { title: "Library fine", lines: [
    ["Student", "Hi, I just got an email saying I owe fifteen dollars in late fees, but I returned those books last week."],
    ["Staff", "Let me check. The system shows two books still out: one on economics and one novel."],
    ["Student", "I put them in the return box outside on Saturday morning."],
    ["Staff", "Ah, the outdoor box isn't scanned until Monday afternoon sometimes. Yes — here they are, returned. I'll cancel the fine now."],
    ["Student", "What a relief. Maybe I'll return things at the front desk from now on."],
  ]},
  { title: "Roommate swap", lines: [
    ["Student", "Hi, I'd like to ask about changing rooms next semester. My roommate and I have very different schedules."],
    ["Staff", "Room changes open in November. Have you two tried setting quiet hours first? We usually require a mediation meeting."],
    ["Student", "We tried for a month. He works night shifts, so he comes in at four in the morning. Neither of us is sleeping well."],
    ["Staff", "That sounds reasonable. Fill out this transfer form, and I'll flag it as a schedule conflict — those get priority."],
    ["Student", "Thank you. He's a nice guy, we just need different rooms."],
  ]},
  { title: "Lost student ID", lines: [
    ["Student", "Hi, I lost my student ID somewhere on campus yesterday. What should I do?"],
    ["Staff", "First, check the lost and found at the student center. If it's not there, a replacement costs twenty dollars."],
    ["Student", "I already checked, and they don't have it. Can I still get into the dining hall tonight?"],
    ["Staff", "I can print you a temporary pass valid for three days, and your new card will be ready tomorrow afternoon."],
    ["Student", "Great. Please freeze the old card too — it has fifty dollars of dining money on it."],
  ]},
],

// ───────────────────────── Read and Select ─────────────────────────
// Real English word, or a fake word? 5 seconds each. (If unsure → No)
realWords: [
  "absorb","accuse","ankle","arrival","blanket","bracelet","brief","cabinet","casual","ceiling",
  "charity","clumsy","collapse","crisp","curtain","decade","delicate","desperate","drawer","eager",
  "elbow","embrace","fabric","faint","fierce","flavor","frown","gentle","glimpse","grateful",
  "harvest","hesitate","hollow","humble","insult","jealous","kneel","ladder","leather","lemon",
  "mature","mild","mineral","narrow","nephew","oblige","obstacle","ordinary","pale","pavement",
  "peculiar","pillow","plead","polish","puzzle","quote","refuge","reluctant","ribbon","rust",
  "scatter","shallow","shiver","slope","sneeze","sober","sprinkle","stubborn","subtle","swift",
  "thread","timber","tremble","urgent","vague","velvet","weave","whisper","witness","wrinkle",
  "anchor","baggage","bargain","blossom","border","breeze","cattle","chapter","cliff","compass",
  "cottage","courage","cradle","dairy","dawn","ditch","dough","drought","feather","fence",
  "flock","fountain","freight","frost","gravel","grief","harbor","hatch","hedge","ivory",
  "journey","kettle","lantern","lawn","linen","marble","meadow","mercy","mist","needle",
  "oath","orchard","parcel","pebble","pier","porridge","quilt","raft","ridge","saddle",
  "shepherd","sleeve","sorrow","stable","stove","straw","stream","swamp","tide","torch",
  "trunk","valley","wagon","wheat","yarn","ladle","gutter","plank","spade","twig",
],
fakeWords: [
  "ablorn","acrupe","antle","arrisle","blasket","brencel","brifty","cabnet","casperal","ceelin",
  "chanity","clunsy","collaple","crispel","curtmin","decage","delibate","desporite","drawel","eagrel",
  "elbrow","embrose","fabrise","fainet","fearcel","flavone","frowst","gentry","glimber","gradeful",
  "harvel","hesibate","hollom","humbel","insolt","jealor","kneelt","laddel","leathen","lemot",
  "matiry","mildon","minerel","narrel","nephil","obline","obstable","ordinure","palet","pavemont",
  "peculier","pillom","pleat","polint","puzzel","quotel","refube","relucent","ribbel","rustel",
  "scattel","shallom","shivel","slopen","sneeber","sobel","sprinkel","stubbern","subtel","swiften",
  "threap","timbel","trembel","urgest","vaguel","velvit","weavel","whispel","witnel","wrinkel",
  "anchel","baggorn","barginal","blossern","bordel","breezon","cattorn","chaptel","cliffen","compise",
  "cottane","couradel","cradorn","dairel","dawnik","ditchel","doughan","droulth","feathom","fencel",
  "flockern","fountel","freitch","frostel","gravorn","griefel","harbel","hatchern","hedgil","ivorn",
  "journel","kettorn","lantel","lawnik","linorn","marbeln","meadorn","mercil","mistorn","needel",
  "oathen","orchel","parceln","pebbeln","pierel","porrigel","quilten","raften","ridgel","saddorn",
  "shepheld","sleevern","sorrowel","stablon","stovel","strawel","streamel","swampern","tidel","torchen",
  "trunkel","vallein","wagorn","wheatel","yarnik","ladorn","guttel","plankern","spaden","twigel",
],

// ───────────────────────── Read and Complete (C-test) ─────────────────────────
// Paragraph where later words are half-deleted; restore them. 3 min each.
cTest: [
  "Coffee is one of the most popular drinks in the world. People in many countries begin their morning with a hot cup of it. The caffeine inside helps them feel awake and ready for work. However, drinking too much coffee late in the day can make it hard to sleep at night.",
  "Public libraries do much more than lend books. Many of them offer free internet access, study rooms, and classes for children and adults. Some libraries even lend tools, musical instruments, and museum passes. For many people, the library is the only quiet place where they can read and think.",
  "Walking is one of the easiest ways to stay healthy. It does not require special equipment or an expensive membership. Doctors say that walking for thirty minutes a day can improve your heart and lower stress. Many people find that a short walk also helps them solve problems and think clearly.",
  "Honey never spoils if it is stored properly. Archaeologists have found pots of honey in ancient tombs that were still safe to eat. The secret lies in its low water content and natural acids, which stop bacteria from growing. This is why honey was also used as medicine in the past.",
  "The first computers filled entire rooms and weighed several tons. They were so expensive that only governments and large companies could afford them. Today, the phone in your pocket is millions of times faster than those early machines. This rapid change has transformed almost every part of modern life.",
  "Sleep plays a key role in learning and memory. While you sleep, your brain reviews what you studied during the day and stores the important parts. Students who stay up all night before an exam often perform worse than those who rest. A regular sleep schedule is one of the best study tools.",
  "Recycling helps reduce the amount of waste that ends up in landfills. Paper, glass, and many plastics can be processed and used again. However, recycling only works well when people sort their trash correctly. A single dirty item can sometimes ruin an entire batch of recyclable material.",
  "Learning a second language changes the way the brain works. Studies show that bilingual people are often better at switching between tasks. They may also develop memory problems later in life than people who speak only one language. It is never too late to start learning.",
  "Bees are essential to the food we eat every day. As they move from flower to flower, they carry pollen that allows plants to produce fruit and seeds. Without bees, many crops such as apples, almonds, and berries would disappear. Protecting them is one of the most important tasks in agriculture.",
  "Small habits can lead to big changes over time. Reading ten pages a day adds up to more than a dozen books each year. Saving a few dollars every week becomes a meaningful amount within a decade. The key is to start small and repeat the action until it feels automatic.",
  "Maps have changed a great deal in the last twenty years. Most people now navigate with their phones instead of paper maps. These apps can warn drivers about traffic and suggest faster routes. However, some experts worry that people are losing the ability to find their way without help.",
  "The tomato was once feared in Europe. Wealthy families ate from pewter plates, and the acid in tomatoes pulled lead from the metal. People who became sick blamed the fruit instead of their dishes. It took centuries for the tomato to become a beloved part of European cooking.",
  "Exercise does not have to mean going to a gym. Taking the stairs instead of the elevator strengthens your legs and heart. Carrying groceries home counts as lifting weights. Doctors agree that the best workout is the one you will actually repeat every week.",
  "Many cities are planting more trees along their streets. Trees provide shade in summer and reduce the temperature of entire neighborhoods. They also absorb noise and clean the air. Studies show that streets with trees even have lower levels of stress among residents.",
  "The first vending machine was invented about two thousand years ago. A Greek engineer designed a device that sold holy water in temples. When a coin was dropped in, its weight opened a small valve. The basic idea remains the same in the machines we use today.",
  "Handwriting activates the brain differently than typing. When students write notes by hand, they must summarize ideas instead of copying every word. This extra effort helps the memory store information more deeply. Many researchers therefore suggest taking at least some notes on paper.",
  "Octopuses are among the most intelligent animals in the ocean. They can open jars, escape from tanks, and solve simple puzzles. Each of their eight arms contains its own network of neurons. Some scientists describe them as creatures with nine brains.",
  "The modern weekend is a fairly recent invention. A century ago, most workers had only Sunday off, if anything. Labor unions fought for decades to win a two-day break. Today, some companies are even experimenting with four-day work weeks.",
  "Libraries in some cities now lend far more than books. Members can borrow sewing machines, telescopes, and even fishing rods. The idea is that rarely used items should be shared rather than owned. This saves money and reduces waste at the same time.",
  "Color affects how people feel in a room. Blue tones tend to calm the mind, which is why they are common in bedrooms. Red raises energy and appetite, making it popular in restaurants. Designers choose colors carefully to shape the mood of a space.",
  "Bicycles remain one of the most efficient machines ever invented. A rider uses less energy per kilometer than a person walking. Bikes require no fuel, produce no pollution, and take little space to park. It is no surprise that many cities are investing in cycling paths.",
  "The human body contains more bacteria than human cells. Most of these tiny organisms live in the digestive system and help break down food. They also train the immune system to recognize real threats. A healthy diet keeps this invisible community in balance.",
  "Airports are designed to guide people without words. Colored lines on the floor lead travelers to gates and exits. Symbols replace sentences so that visitors from any country can find their way. Even the lighting is planned to keep crowds calm and moving.",
  "Saving money is easier when it happens automatically. Many banks let customers move a small amount into savings every payday. Because the transfer happens before spending begins, people rarely miss the money. Over several years, these small amounts grow into a real safety net.",
],

// ───────────────────────── Fill in the Blanks ─────────────────────────
// One sentence, one damaged word: first half shown, type the missing letters. 20s.
fillBlanks: [
  { s: "She opened the window to let in some fresh", w: "air" },
  { s: "He was too tired to finish his", w: "homework" },
  { s: "The train arrived ten minutes behind", w: "schedule" },
  { s: "Please write your name at the top of the", w: "page" },
  { s: "The doctor told him to take the medicine twice a", w: "day" },
  { s: "We could not see the mountains because of the thick", w: "fog" },
  { s: "She put the milk back in the", w: "refrigerator" },
  { s: "The audience clapped loudly at the end of the", w: "performance" },
  { s: "You need a password to connect to the wireless", w: "network" },
  { s: "The children built a sandcastle on the", w: "beach" },
  { s: "He apologized for arriving late to the", w: "meeting" },
  { s: "The recipe says to bake the cake for forty", w: "minutes" },
  { s: "I always check the weather forecast before leaving the", w: "house" },
  { s: "The museum displays paintings from the nineteenth", w: "century" },
  { s: "She turned off the lights to save", w: "electricity" },
  { s: "The students raised their hands to answer the", w: "question" },
  { s: "He keeps his important documents in a locked", w: "drawer" },
  { s: "The bridge was closed for repairs over the", w: "weekend" },
  { s: "Drink plenty of water to avoid", w: "dehydration" },
  { s: "The waiter brought the bill at the end of the", w: "meal" },
  { s: "The plane landed safely despite the strong", w: "wind" },
  { s: "Her speech lasted about twenty", w: "minutes" },
  { s: "Wear a helmet whenever you ride your", w: "bicycle" },
  { s: "The store offers a full refund within thirty", w: "days" },
  { s: "He locked the door and put the key in his", w: "pocket" },
  { s: "The baby finally fell asleep after midnight", w: "" , skip: true },
  { s: "She watered the plants on the balcony every", w: "morning" },
  { s: "The team scored in the final minute of the", w: "game" },
  { s: "Don't forget to bring your swimsuit to the", w: "pool" },
  { s: "The letter arrived three weeks after it was", w: "sent" },
  { s: "He whispered so the children would not", w: "hear" },
  { s: "The mountain peak was covered in", w: "snow" },
  { s: "She signed the contract with a blue", w: "pen" },
  { s: "The smoke alarm went off while he was", w: "cooking" },
  { s: "They planted roses along the garden", w: "fence" },
  { s: "The dentist said I should floss every", w: "night" },
  { s: "We watched the fireworks from the hotel", w: "balcony" },
  { s: "The printer is out of paper and", w: "ink" },
  { s: "Her grandfather tells the same stories at every family", w: "dinner" },
  { s: "The ferry crosses the river every twenty", w: "minutes" },
  { s: "Loud music from the party kept the whole street", w: "awake" },
  { s: "He saved his essay twice in case the computer", w: "crashed" },
  { s: "The actor forgot his lines in the middle of the", w: "play" },
  { s: "Fresh vegetables are cheaper at the farmers", w: "market" },
  { s: "The librarian helped me find the right", w: "book" },
  { s: "A strong password should include numbers and", w: "symbols" },
  { s: "The tour guide spoke three languages", w: "fluently" },
  { s: "The puppy chewed a hole in my favorite", w: "shoe" },
  { s: "They postponed the picnic because of the", w: "rain" },
  { s: "The nurse checked the patient's temperature every", w: "hour" },
  { s: "I set two alarms so I would not miss my", w: "flight" },
  { s: "The audience stood and clapped when the song", w: "ended" },
  { s: "He sharpened his pencil before the", w: "exam" },
  { s: "The waiter recommended the soup of the", w: "day" },
].filter(x => !x.skip),

// ───────────────────────── Writing prompts ─────────────────────────
writingSample: [
  "Some people prefer to plan every detail of their future, while others prefer to keep their options open. Which approach do you prefer, and why?",
  "Do you think students should be graded on effort as well as results? Explain your opinion with reasons and examples.",
  "Many cities are building more bike lanes instead of car lanes. Is this a good idea? Why or why not?",
  "Some people believe everyone should spend at least a year living in another country. Do you agree or disagree?",
  "Is it better to be a specialist who knows one field deeply, or a generalist who knows many fields broadly? Explain your view.",
  "Do you think exams are the best way to measure what students have learned? Why or why not?",
  "Some people think that childhood is the happiest time of life. Do you agree or disagree? Use examples.",
  "Should universities require students to do volunteer work before graduating? Explain your opinion.",
  "Many people now listen to audiobooks instead of reading. Do you think listening counts as reading? Explain.",
  "Is competition among students helpful or harmful to learning? Support your answer with examples.",
  "Some people think that success is mostly about luck, while others believe it is mostly about effort. What is your view?",
  "Should companies allow employees to work from home permanently? Discuss the advantages and disadvantages.",
  "Many schools are replacing textbooks with tablets. Is this a positive change? Explain your opinion.",
  "Do you think people today have more stress than people fifty years ago? Why or why not?",
  "Some people believe pets should be treated like family members. Do you agree or disagree?",
  "Is it better to save money for the future or to spend it enjoying the present? Explain your view.",
  "Should fast food companies be allowed to advertise to children? Explain your opinion.",
  "Some people think city parks are a waste of valuable land. Do you agree or disagree? Use examples.",
  "Do you believe that grades motivate students to learn, or do they create unnecessary pressure? Explain.",
  "Many people share their entire lives online. What are the benefits and risks of this habit?",
  "Should students evaluate their teachers at the end of each course? Why or why not?",
  "Some believe that breakfast is the most important meal of the day. Do you agree? Explain your view.",
  "Is it better for children to grow up in the city or in the countryside? Support your opinion with examples.",
  "Do you think machines will ever fully replace human teachers? Why or why not?",
],
interactiveWriting: [
  { main: "Describe a person who has had a strong influence on your life. Explain who they are and how they influenced you.",
    follow: "Now write about one specific moment with this person that you will never forget." },
  { main: "Some people think money spent on space exploration should be used to solve problems on Earth. What is your opinion?",
    follow: "Now describe one specific benefit that space research has brought to everyday life." },
  { main: "Describe a challenge that students face today that their parents did not face. Explain why it is difficult.",
    follow: "Now suggest one realistic way that schools could help students with this challenge." },
  { main: "Do you prefer learning online or in a classroom? Explain your preference with reasons and examples.",
    follow: "Now describe one thing about your less-preferred option that you actually appreciate." },
  { main: "Describe a goal you achieved that required a long time and a lot of effort.",
    follow: "Now explain what you would do differently if you had to pursue the same goal again." },
  { main: "Some people believe social media does more harm than good for young people. What do you think?",
    follow: "Now describe one rule about social media use that you think every family should consider." },
  { main: "Describe a place in your country that you think every visitor should see. Explain why it is special.",
    follow: "Now describe the best time of year to visit this place and what a visitor should do there." },
  { main: "Do you think students learn more from success or from failure? Explain your opinion with examples.",
    follow: "Now describe a specific failure from your own life and what it taught you." },
  { main: "Describe a piece of technology you could not live without. Explain why it is so important to you.",
    follow: "Now imagine this technology disappeared tomorrow. Describe how your daily life would change." },
  { main: "Some people prefer to work in teams, while others prefer to work alone. Which do you prefer and why?",
    follow: "Now describe a situation where your less-preferred working style would actually be better." },
  { main: "Describe a tradition from your culture that you would like to pass on to future generations.",
    follow: "Now explain one way this tradition has already changed compared to your grandparents' time." },
  { main: "Is it more important for a city to build new housing or to protect historic buildings? Explain your view.",
    follow: "Now describe a building or neighborhood you know that shows why your opinion matters." },
  { main: "Describe a time when you had to adapt to a big change in your life.",
    follow: "Now explain what advice you would give to someone facing a similar change." },
  { main: "Some people think university education should be free for everyone. Do you agree or disagree?",
    follow: "Now describe one problem that might appear if your opinion became policy, and how to solve it." },
],

// ───────────────────────── Photos (Speak/Write About the Photo) ─────────────────────────
// Stable seeded images. Describe: where, who/what, actions, details, guesses.
photoSeeds: [
  "market","kitchen","library","beach2","mountain","city-street","garden","train",
  "coffee-shop","park-bench","bridge","forest","harbor","classroom","stadium","museum1",
  "desert","lake","rooftop","snow","festival","farm","office2","subway",
],

// ───────────────────────── 7-week plan (from the prep doc) ─────────────────────────
plan: [
  { range: "6/11 – 6/21", title: "第 1 周：摸底 + 熟悉题型", items: ["看官方走查视频、通读官方指南", "做 1 次官方免费模拟测试（基线）", "设备检查：Chrome、摄像头、麦克风"] },
  { range: "6/22 – 7/5",  title: "第 2–3 周：分题型专项", items: ["口语每天 25 分钟（一三五即兴问答 / 二四长口语）", "其他单项每天 25 分钟轮换", "周末官方模拟测试 1 次", "6 月底购买第一次正式考试"] },
  { range: "7/6 – 7/12",  title: "第 4 周：第一次正式考试", items: ["考前 2 天只做模拟 + 保持口语手感", "7 月上旬考第一次", "Speaking ≥125 且满意 → 送分完成"] },
  { range: "7/13 – 7/26", title: "第 5–6 周：补弱项 + 二战（如需要）", items: ["针对最弱单项专项 10 天", "7 月下旬考第二次"] },
  { range: "7/27 – 8/17", title: "第 7 周：缓冲 + 送分", items: ["如需要 8/1 前考第三次", "8/10 前送分给 USF 并通知系里注册", "8/17 注册截止 ✅"] },
],
planStart: "2026-06-11",
};
